# Generated by Django 3.2.3 on 2022-02-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image1', models.FileField(null=True, upload_to='')),
                ('Image2', models.FileField(null=True, upload_to='')),
                ('Image3', models.FileField(null=True, upload_to='')),
                ('Image4', models.FileField(null=True, upload_to='')),
                ('Image5', models.FileField(null=True, upload_to='')),
                ('Before_price', models.FloatField()),
                ('After_price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('choice', models.CharField(choices=[('Smart Phone', 'Smart Phone'), ('Camera', 'Camera'), ('Games', 'Games'), ('Smart Speakers', 'Smart Speakers'), ('Smart Watch', 'Smart Watch'), ('Tablets', 'Tablets'), ('Laptops', 'Laptops'), ('Mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('Headphone', 'Headphone'), ('Monitors', 'Monitors')], default=None, max_length=100)),
                ('Description1title', models.CharField(max_length=100)),
                ('Description2title', models.CharField(max_length=100)),
                ('Description3title', models.CharField(max_length=100)),
                ('Description4title', models.CharField(max_length=100)),
                ('Description1', models.TextField()),
                ('Description2', models.TextField()),
                ('Description3', models.TextField()),
                ('Description4', models.TextField()),
                ('Buy_link', models.URLField()),
                ('Dateofpublished', models.DateTimeField(auto_now_add=True)),
                ('Brand', models.CharField(max_length=100)),
                ('Colour', models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Pink', 'Pink'), ('Green', 'Green'), ('Sky Blue', 'Sky Blue'), ('Yellow', 'Yellow'), ('Black', 'Black')], default=None, max_length=50)),
                ('Memory', models.CharField(blank=True, default=None, max_length=200)),
                ('cellular_technology', models.CharField(blank=True, default=None, max_length=200)),
                ('Included_items', models.CharField(blank=True, default=None, max_length=200)),
                ('Camera_quality', models.CharField(blank=True, default=None, max_length=200)),
                ('Model', models.CharField(blank=True, default=None, max_length=200)),
                ('screensize', models.CharField(blank=True, default=None, max_length=200)),
                ('RAM', models.CharField(blank=True, default=None, max_length=200)),
                ('ROM', models.CharField(blank=True, default=None, max_length=200)),
                ('Resolution', models.CharField(blank=True, default=None, max_length=200)),
                ('displaytype', models.CharField(blank=True, default=None, max_length=200)),
                ('Genre', models.CharField(blank=True, default=None, max_length=200)),
                ('Mode', models.CharField(blank=True, default=None, max_length=200)),
                ('releasedate', models.DateTimeField(auto_now_add=True)),
                ('Bluetoothconnectivity', models.CharField(blank=True, default=None, max_length=200)),
                ('waterresistance', models.CharField(blank=True, default=None, max_length=200)),
                ('connectivitytype', models.CharField(blank=True, default=None, max_length=200)),
                ('storage', models.CharField(blank=True, default=None, max_length=200)),
                ('Zoom', models.CharField(blank=True, default=None, max_length=200)),
                ('Graphicscoprocessor', models.CharField(blank=True, default=None, max_length=200)),
                ('Batterylife', models.CharField(blank=True, default=None, max_length=200)),
                ('compatibledevices', models.CharField(blank=True, default=None, max_length=200)),
                ('Refreshrate', models.CharField(blank=True, default=None, max_length=200)),
                ('Supportedinternetservices', models.CharField(blank=True, default=None, max_length=200)),
                ('Specialfeatures', models.CharField(blank=True, default=None, max_length=200)),
                ('series', models.CharField(blank=True, default=None, max_length=200)),
            ],
            options={
                'verbose_name': 'Product',
                'get_latest_by': ['-Dateofpublished'],
            },
        ),
    ]
