# Generated by Django 3.2.3 on 2022-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheaptechguys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('Smart Phone', 'Smart Phone'), ('Camera', 'Camera'), ('Games', 'Games'), ('Smart Speakers', 'Smart Speakers'), ('Smart Watch', 'Smart Watch'), ('Tablets', 'Tablets'), ('Laptops', 'Laptops'), ('Mouse', 'Mouse'), ('keyboard', 'Keyboard'), ('Headphone', 'Headphone'), ('Monitors', 'Monitors'), ('TV', 'TV')], default=None, max_length=100),
        ),
    ]
